/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#653e00",
        "primary": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "surface-container-lowest": "#060e20",
        "surface-variant": "#2d3449",
        "surface-dim": "#0b1326",
        "error": "#ffb4ab",
        "secondary-container": "#00a572",
        "tertiary-fixed": "#ffddb8",
        "error-container": "#93000a",
        "secondary": "#4edea3",
        "on-primary-fixed-variant": "#004395",
        "on-secondary": "#003824",
        "outline": "#8c909f",
        "on-surface": "#dae2fd",
        "tertiary": "#ffb95f",
        "background": "#0b1326",
        "inverse-primary": "#005ac2",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2d3449",
        "on-background": "#dae2fd",
        "surface-container-low": "#131b2e",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "on-error": "#690005",
        "on-tertiary-fixed": "#2a1700",
        "inverse-on-surface": "#283044",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#424754",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#3e2400",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "surface": "#0b1326",
        "inverse-surface": "#dae2fd",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#ca8100",
        "surface-container": "#171f33",
        "primary-fixed": "#d8e2ff",
        "on-primary": "#002e6a",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary-container": "#00311f",
        "surface-tint": "#adc6ff",
        "surface-container-high": "#222a3d",
        "on-tertiary": "#472a00",
        "on-surface-variant": "#c2c6d6"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-xs": "4px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-xl": "40px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-md": ["Geist"],
        "metric-xl": ["Geist"],
        "headline-lg": ["Geist"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Geist"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "metric-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  darkMode: "class",
  plugins: [],
}
